theme: jekyll-theme-merlot
Фитнес студия АКТИВ Королев
Актив фитнес студия Адрес: 141077 г. Королев, Октябрьский бульвар, дом 5.
http://activf2017.blogspot.com/
[activf2017.blogspot.com](http://activf2017.blogspot.com/)
![Актив фитнес студия Королёв](https://avatars1.githubusercontent.com/u/37883500?s=200&v=4)
